### PR TITLE
Crypto refactor

### PR DESCRIPTION
**Pull request by ajpauwels**

### CODE REVIEW

**Comment by capt-haddock** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ajpauwels**
You can assign the PR to them by writing `/assign @ajpauwels` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=pauwels-labs%2Fredact-store).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/pauwels-labs/redact-store/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 9095e37fb0c1b763ee6a02f3ff67cf25ec571784 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/abs-redact-store-pr-7-build-prod-xxfb7) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 9095e37fb0c1b763ee6a02f3ff67cf25ec571784 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/abs-redact-store-pr-7-build-prod-xxfb7) | `/test build-prod`
build-alpine | 9095e37fb0c1b763ee6a02f3ff67cf25ec571784 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/s-redact-store-pr-7-build-alpine-hmmcs) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-alpine | 9095e37fb0c1b763ee6a02f3ff67cf25ec571784 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/s-redact-store-pr-7-build-alpine-hmmcs) | `/test build-alpine`
build-prod | c9217b2ce0641770565a5f7f39605c0ca9834df5 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/abs-redact-store-pr-7-build-prod-jtcx9) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | c9217b2ce0641770565a5f7f39605c0ca9834df5 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/abs-redact-store-pr-7-build-prod-jtcx9) | `/test build-prod`
build-alpine | c9217b2ce0641770565a5f7f39605c0ca9834df5 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/s-redact-store-pr-7-build-alpine-qz6rk) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | c9217b2ce0641770565a5f7f39605c0ca9834df5 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/abs-redact-store-pr-7-build-prod-jtcx9) | `/test build-prod`
build-alpine | c9217b2ce0641770565a5f7f39605c0ca9834df5 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/s-redact-store-pr-7-build-alpine-qz6rk) | `/test build-alpine`
unit-test | c9217b2ce0641770565a5f7f39605c0ca9834df5 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/labs-redact-store-pr-7-unit-test-q8wbg) | `/test unit-test`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-alpine | c9217b2ce0641770565a5f7f39605c0ca9834df5 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/s-redact-store-pr-7-build-alpine-qz6rk) | `/test build-alpine`
build-prod | 1ad995d2cf0a9f0a82b150a450e3f1161c45b221 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/abs-redact-store-pr-7-build-prod-ctgdl) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 1ad995d2cf0a9f0a82b150a450e3f1161c45b221 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/abs-redact-store-pr-7-build-prod-ctgdl) | `/test build-prod`
build-alpine | 1ad995d2cf0a9f0a82b150a450e3f1161c45b221 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/s-redact-store-pr-7-build-alpine-6f9xw) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ajpauwels** [comment]
Closing as this has been merged into #8

**Pull request closed without merging**
