### PR TITLE
Remove the collection request and query params

### PR DESCRIPTION
**Pull request by howhelan**

### CODE REVIEW

**Comment by capt-haddock** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **howhelan**
You can assign the PR to them by writing `/assign @howhelan` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=pauwels-labs%2Fredact-store).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/pauwels-labs/redact-store/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by capt-haddock** [comment]
@howhelan: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 536ecef90dd508d3430e983e8785ab9f04648b12 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-mphc6) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by ajpauwels — APPROVED** [review]

**Comment by capt-haddock** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ajpauwels](https://github.com/pauwels-labs/redact-store/pull/5#pullrequestreview-688664366 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=pauwels-labs%2Fredact-store).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/pauwels-labs/redact-store/blob/main/OWNERS)~~ [ajpauwels]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by capt-haddock** [comment]
@howhelan: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 536ecef90dd508d3430e983e8785ab9f04648b12 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-mphc6) | `/test build-prod`
build-alpine | 536ecef90dd508d3430e983e8785ab9f04648b12 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-w8t5c) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@howhelan: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 536ecef90dd508d3430e983e8785ab9f04648b12 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-mphc6) | `/test build-prod`
build-alpine | 536ecef90dd508d3430e983e8785ab9f04648b12 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-w8t5c) | `/test build-alpine`
unit-test | 536ecef90dd508d3430e983e8785ab9f04648b12 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/unit-test-bxgf9) | `/test unit-test`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@howhelan: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-alpine | 536ecef90dd508d3430e983e8785ab9f04648b12 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-w8t5c) | `/test build-alpine`
unit-test | 536ecef90dd508d3430e983e8785ab9f04648b12 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/unit-test-bxgf9) | `/test unit-test`
build-prod | 57240a9d978ab1de1055b1f63a0200dc41e00579 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-p9pmx) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@howhelan: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-test | 536ecef90dd508d3430e983e8785ab9f04648b12 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/unit-test-bxgf9) | `/test unit-test`
build-prod | 57240a9d978ab1de1055b1f63a0200dc41e00579 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-p9pmx) | `/test build-prod`
build-alpine | 57240a9d978ab1de1055b1f63a0200dc41e00579 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-l2tsr) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@howhelan: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 57240a9d978ab1de1055b1f63a0200dc41e00579 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-p9pmx) | `/test build-prod`
build-alpine | 57240a9d978ab1de1055b1f63a0200dc41e00579 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-l2tsr) | `/test build-alpine`
unit-test | 57240a9d978ab1de1055b1f63a0200dc41e00579 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/unit-test-dg9ms) | `/test unit-test`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@howhelan: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 57240a9d978ab1de1055b1f63a0200dc41e00579 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-p9pmx) | `/test build-prod`
unit-test | 57240a9d978ab1de1055b1f63a0200dc41e00579 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/unit-test-dg9ms) | `/test unit-test`
build-alpine | 7259abfed2ba88513bfb7b8858deb8c8fbff086d | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-29lsl) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@howhelan: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
unit-test | 57240a9d978ab1de1055b1f63a0200dc41e00579 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/unit-test-dg9ms) | `/test unit-test`
build-alpine | 7259abfed2ba88513bfb7b8858deb8c8fbff086d | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-29lsl) | `/test build-alpine`
build-prod | 7259abfed2ba88513bfb7b8858deb8c8fbff086d | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-sfthv) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
