### PR TITLE
feat: add key support

### PR DESCRIPTION
**Pull request by ajpauwels**
- Adds standard data types for representing keys
  - These should be split into a shared crate for the client to use
- Added GET and POST endpoints for creating and fetching keys
- Upgraded mongodb driver to make use of new collection_with_type methods

### CODE REVIEW

**Comment by capt-haddock** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **capt-haddock**
You can assign the PR to them by writing `/assign @capt-haddock` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=pauwels-labs%2Fredact-store).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/pauwels-labs/redact-store/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 2c2d96918316fc86caea9ab9df9ea75342fd41f1 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-r9955) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 0a061a9b24177c1d8c46a7c5074f087d939d870f | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-tk6s4) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 707e433bc787c0d52afa152f854d0e5835426d6e | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-rsvxf) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | b87ef545ab1286f42caf16fc1d03ceedc9953ebf | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-nf9pg) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | e669e59f2a05214fc4f8f5cad1a0142484cff633 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-hgkjb) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | e669e59f2a05214fc4f8f5cad1a0142484cff633 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-hgkjb) | `/test pr`
build-alpine | 003101ba294abb14339a85e15cbaf4aab35074ec | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-sgthm) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | e669e59f2a05214fc4f8f5cad1a0142484cff633 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-hgkjb) | `/test pr`
build-alpine | 003101ba294abb14339a85e15cbaf4aab35074ec | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-sgthm) | `/test build-alpine`
build-prod | 003101ba294abb14339a85e15cbaf4aab35074ec | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-q7jvv) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | e669e59f2a05214fc4f8f5cad1a0142484cff633 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-hgkjb) | `/test pr`
build-alpine | 003101ba294abb14339a85e15cbaf4aab35074ec | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-sgthm) | `/test build-alpine`
build-prod | 6720b01a74f5630d59d2c9f12e47e9a531a97c15 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-b6whz) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-alpine | 003101ba294abb14339a85e15cbaf4aab35074ec | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-sgthm) | `/test build-alpine`
build-prod | 6720b01a74f5630d59d2c9f12e47e9a531a97c15 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-b6whz) | `/test build-prod`
pr | 003101ba294abb14339a85e15cbaf4aab35074ec | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-cvtwl) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 6720b01a74f5630d59d2c9f12e47e9a531a97c15 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-b6whz) | `/test build-prod`
pr | 003101ba294abb14339a85e15cbaf4aab35074ec | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-cvtwl) | `/test pr`
build-alpine | 6720b01a74f5630d59d2c9f12e47e9a531a97c15 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-dztjh) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 6720b01a74f5630d59d2c9f12e47e9a531a97c15 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-b6whz) | `/test build-prod`
build-alpine | 6720b01a74f5630d59d2c9f12e47e9a531a97c15 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-dztjh) | `/test build-alpine`
pr | 6720b01a74f5630d59d2c9f12e47e9a531a97c15 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-gq8t4) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 6720b01a74f5630d59d2c9f12e47e9a531a97c15 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-b6whz) | `/test build-prod`
pr | 6720b01a74f5630d59d2c9f12e47e9a531a97c15 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-gq8t4) | `/test pr`
build-alpine | 62231d66cb7b78238ffdc27eb426061cdca7d549 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-r5vf9) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 6720b01a74f5630d59d2c9f12e47e9a531a97c15 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-gq8t4) | `/test pr`
build-alpine | 62231d66cb7b78238ffdc27eb426061cdca7d549 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-r5vf9) | `/test build-alpine`
build-prod | 62231d66cb7b78238ffdc27eb426061cdca7d549 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-l2cxh) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-alpine | 62231d66cb7b78238ffdc27eb426061cdca7d549 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-r5vf9) | `/test build-alpine`
build-prod | 62231d66cb7b78238ffdc27eb426061cdca7d549 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-l2cxh) | `/test build-prod`
pr | 62231d66cb7b78238ffdc27eb426061cdca7d549 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-rfcww) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by howhelan — APPROVED** [review]

**Comment by capt-haddock** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[howhelan](https://github.com/pauwels-labs/redact-store/pull/4#pullrequestreview-661113579 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **capt-haddock**
You can assign the PR to them by writing `/assign @capt-haddock` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=pauwels-labs%2Fredact-store).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/pauwels-labs/redact-store/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by capt-haddock** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **capt-haddock**
You can assign the PR to them by writing `/assign @capt-haddock` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=pauwels-labs%2Fredact-store).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/pauwels-labs/redact-store/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 62231d66cb7b78238ffdc27eb426061cdca7d549 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-l2cxh) | `/test build-prod`
pr | 62231d66cb7b78238ffdc27eb426061cdca7d549 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-rfcww) | `/test pr`
build-alpine | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-sjp76) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 62231d66cb7b78238ffdc27eb426061cdca7d549 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-rfcww) | `/test pr`
build-alpine | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-sjp76) | `/test build-alpine`
build-prod | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-nt6fb) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-alpine | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-sjp76) | `/test build-alpine`
build-prod | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-nt6fb) | `/test build-prod`
pr | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-cd7bg) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **capt-haddock**
You can assign the PR to them by writing `/assign @capt-haddock` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=pauwels-labs%2Fredact-store).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/pauwels-labs/redact-store/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-alpine | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-sjp76) | `/test build-alpine`
pr | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-cd7bg) | `/test pr`
build-prod | 6362cc0f299a244fa12f74b31baadd834504d3fe | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-5xtgs) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-alpine | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-sjp76) | `/test build-alpine`
pr | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-cd7bg) | `/test pr`
build-prod | 8185dfbda77a21fbc1ea126a95adebf6d39b4732 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-nqvjq) | `/test build-prod`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | d87652cf642f25c98d14bae06d273a30db7d77ad | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-cd7bg) | `/test pr`
build-prod | 8185dfbda77a21fbc1ea126a95adebf6d39b4732 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-nqvjq) | `/test build-prod`
build-alpine | 6362cc0f299a244fa12f74b31baadd834504d3fe | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-6hhsc) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 8185dfbda77a21fbc1ea126a95adebf6d39b4732 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-nqvjq) | `/test build-prod`
build-alpine | 6362cc0f299a244fa12f74b31baadd834504d3fe | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-6hhsc) | `/test build-alpine`
pr | 8185dfbda77a21fbc1ea126a95adebf6d39b4732 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-5c42m) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 8185dfbda77a21fbc1ea126a95adebf6d39b4732 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-nqvjq) | `/test build-prod`
pr | 8185dfbda77a21fbc1ea126a95adebf6d39b4732 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-5c42m) | `/test pr`
build-alpine | 8185dfbda77a21fbc1ea126a95adebf6d39b4732 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-pv646) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 8185dfbda77a21fbc1ea126a95adebf6d39b4732 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-nqvjq) | `/test build-prod`
build-alpine | 8185dfbda77a21fbc1ea126a95adebf6d39b4732 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-pv646) | `/test build-alpine`
pr | 6362cc0f299a244fa12f74b31baadd834504d3fe | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-42hdb) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-prod | 8185dfbda77a21fbc1ea126a95adebf6d39b4732 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-prod-nqvjq) | `/test build-prod`
pr | 6362cc0f299a244fa12f74b31baadd834504d3fe | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-42hdb) | `/test pr`
build-alpine | 95ec6d8bb25148d0ec84ed217082ba0fd0912ef0 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-hb8ss) | `/test build-alpine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-alpine | 95ec6d8bb25148d0ec84ed217082ba0fd0912ef0 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-hb8ss) | `/test build-alpine`
pr | 95ec6d8bb25148d0ec84ed217082ba0fd0912ef0 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-lb7n5) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
@ajpauwels: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
build-alpine | 95ec6d8bb25148d0ec84ed217082ba0fd0912ef0 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/build-alpine-hb8ss) | `/test build-alpine`
pr | 104b21cece66b8eab97f55f0b227619fc130e417 | [link](http://dashboard.dev.pauwelslabs.com/namespaces/jx/pipelineruns/pr-brznb) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by capt-haddock** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **capt-haddock**
You can assign the PR to them by writing `/assign @capt-haddock` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=pauwels-labs%2Fredact-store).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/pauwels-labs/redact-store/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by capt-haddock** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[ajpauwels](https://github.com/pauwels-labs/redact-store/pull/4#issuecomment-850340108 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **capt-haddock**
You can assign the PR to them by writing `/assign @capt-haddock` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=pauwels-labs%2Fredact-store).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/pauwels-labs/redact-store/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
